name: Deployment Workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  job_one:
    name: Auto Pull
    runs-on: ubuntu-latest
    steps:
      - name: pulling changes from master
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: dscxuser
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          port: 22
          script: |
            cd /home/dscxuser/omg-frames-api/
            git pull origin master
            source ./venv/bin/activate
            pip install -r requirements.txt
            deactivate
            sudo systemctl restart omg-frames-api.service
